services:
  php_apache:
    container_name: php-apache
    image: php:8.2-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - my_network

  db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: recrutamento
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "9906:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - my_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - my_network

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    ports:
      - "8082:8080"  # Expondo o cAdvisor na porta 8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Necessário para o cAdvisor acessar os dados do Docker
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
