global:
  scrape_interval: 15s  # Intervalo de coleta das métricas

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # cAdvisor expõe métricas na porta 8080
